banner:
  enable: true
  title: 
    - 绘
    - 素
    - の
    - Blog
  border: false
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

avatar:
  enable: true
  url: /images/avatar.jpg
  rounded: true
  opacity: 1