banner:
  enable: true
  title: 
    - 绘
    - 素
    - の
    - Blog
  border: false
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

say:
  enable: false

avatar:
  enable: true
  url: /images/avatar.jpg
  rounded: true
  opacity: 1
  
menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: 你猜
  custom:
    title: Twitter
    path: https://twitter.com/huisudesu/
    icon: ri:twitter-line

pages:

post_meta:
  item_text: false
  created_at: true
  updated_at: false
  categories: true
  tags: true

footer:
  since: 2022
  powered:
    enable: false

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

comment:
  enable: true

wordcloud:
  enable: true
  height: 350

katex:
  copy_tex: true
  global: true
  options: {}
  
codeblock:
  copy_btn: true

reward: false